races = [
    "Antling",
    "Badgerling",
    "Batling",
    "Beetleling",
    "Boarling",
    "Cricketling",
    "Deerling",
    "Duckling",
    "Eelling",
    "Elf",
    "Fishling",
    "Flealing",
    "Flyling",
    "Foxling",
    "Frogling",
    "Gnome",
    "Goatling",
    "Goblin",
    "Gooseling",
    "Hawkling",
    "Hedgehogling",
    "Houndling",
    "Human",
    "Magepieling",
    "Moleling",
    "Mothling",
    "Mouseling",
    "Newtling",
    "Owlling",
    "Rabbitling",
    "Ratling",
    "Ravenling",
    "Slothling",
    "Slugling",
    "Sparrowling",
    "Spiderling",
    "Swanling",
    "Toadling",
    "Weaselling",
    "Wormling"
]

classes = [
    "Barbarian",
    "Fighter",
    "Hunter",
    "Knight",
    "Monk",
    "Sorcerer",
    "Summoner",
    "Thief",
    "Wizard"
]

wizard_archetypes = [
    "Animist",
    "Biomancer",
    "Curse-Eater",
    "Drowned",
    "Elementalist",
    "Elf",
    "Garden",
    "Geometer",
    "Illusionist",
    "Necromancer",
    "Orthodox",
    "Spider",
    "White Hand"
]
